### ISSUE TITLE
DataLinkError: (Status 403)  - Cant load data from API

### ISSUE THREAD

**Issue by abstractumx** [Nasdaq/data-link-python#21]
Hi, i am having this issue when i try to load the API table. How can I solve this?
__________________________________

DataLinkError: (Status 403) Something went wrong. Please try again. If you continue to have problems, please contact us at connect@data.nasdaq.com.
__________________________________

Code:

import nasdaqdatalink

nasdaq_api_key ='my-key'
nasdaqdatalink.read_key(nasdaq_api_key)

df = nasdaqdatalink.get_table('MER/F1', paginate=True)
df

**Comment by couture-ql** [comment]
Hoping you did reach out to support and resolve your issues.  Will be closing as 403s are due to lack of access, rather than a bug in the SDK itself.
