### ISSUE TITLE
How can I get the same value as with this link?  ‘https://api.nasdaq.com/api/quote/IBM/historical?assetclass=stocks&fromdate=2019-10-07&limit=30&random=45 ?

### ISSUE THREAD

**Issue by thedrewen** [Nasdaq/data-link-python#49]
Hello, 

I've just discovered the bookshop,
The first time I used the api I used this link but unfortunately after a few requests all my vps can no longer reach nasdaq so I found this library but I can't find how to access the same data as https://api.nasdaq.com/api/quote/IBM/historical?assetclass=stocks&fromdate=2019-10-07&limit=30&random=45.

Thanks

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you for contacting us.

Kindly be advised that our API only supports products available on the
Nasdaq Data Link platform (https://data.nasdaq.com [1]). Our API and
tools are incompatible with the data on api.nasdaq.com [2] as this is
different from Nasdaq Data Link&#039;s API.

You may view our product offerings by navigating to
https://data.nasdaq.com/search [3].

Please let us know should you have additional questions or concerns.
We look forward to assisting you.

Thanks,


Links:
------
[1] https://data.nasdaq.com/
[2] http://api.nasdaq.com
[3] https://data.nasdaq.com/search

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/742626220/record/8281983524/1/
[3]
https://secure.helpscout.net/satisfaction/742626220/record/8281983524/2/
[4]
https://secure.helpscout.net/satisfaction/742626220/record/8281983524/3/

**Comment by frg004** [comment]
Hi there,
I need to get the following data for example for one stock :
```
{
          "date": "10/24/2024",
          "close": "$218.39",
          "volume": "11,193,440",
          "open": "$220.80",
          "high": "$221.32",
          "low": "$216.16"
        },
```
How can I get them using your api? Is it possible?
If not, which api should I use? 
Thank you!

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you for reaching out.

To help us look more closely into your inquiry, could you please send
us an email at ***@***.*** [1]? This will allow us to
assist you best.

Best regards,
Nasdaq Data Link


Links:
------
[1] ***@***.***

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/742652653/record/8282158137/1/
[3]
https://secure.helpscout.net/satisfaction/742652653/record/8282158137/2/
[4]
https://secure.helpscout.net/satisfaction/742652653/record/8282158137/3/

**Comment by frg004** [comment]
I would love to but I can't read your email.

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you for reaching out.

To help us look more closely into your inquiry, could you please send
us an email at ***@***.*** [1]? This will allow us to
assist you best.

Best regards,
Nasdaq Data Link


Links:
------
[1] ***@***.***

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/742653595/record/8282171280/1/
[3]
https://secure.helpscout.net/satisfaction/742653595/record/8282171280/2/
[4]
https://secure.helpscout.net/satisfaction/742653595/record/8282171280/3/

**Comment by thedrewen** [comment]
![image](https://github.com/user-attachments/assets/096b6d39-da64-4836-a462-90166ed56745)

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you for reaching out.

To help us look more closely into your inquiry, could you please send
us an email at ***@***.*** [1]? This will allow us to
assist you best.

Best regards,
Nasdaq Data Link


Links:
------
[1] ***@***.***

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/742654139/record/8282179270/1/
[3]
https://secure.helpscout.net/satisfaction/742654139/record/8282179270/2/
[4]
https://secure.helpscout.net/satisfaction/742654139/record/8282179270/3/

**Comment by thedrewen** [comment]
![image](https://github.com/user-attachments/assets/3cc29362-8c72-4653-8122-c4a64d016c3d)
We can't see the email.

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you for reaching out.

To help us look more closely into your inquiry, could you please send
us an email at ***@***.*** [1]? This will allow us to
assist you best.

Best regards,
Nasdaq Data Link


Links:
------
[1] ***@***.***

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/742654851/record/8282189698/1/
[3]
https://secure.helpscout.net/satisfaction/742654851/record/8282189698/2/
[4]
https://secure.helpscout.net/satisfaction/742654851/record/8282189698/3/

**Comment by thedrewen** [comment]
4 Not good

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you for reaching out.

To help us look more closely into your inquiry, could you please send
us an email at ***@***.*** [1]? This will allow us to
assist you best.

Best regards,
Nasdaq Data Link


Links:
------
[1] ***@***.***

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/742655379/record/8282198633/1/
[3]
https://secure.helpscout.net/satisfaction/742655379/record/8282198633/2/
[4]
https://secure.helpscout.net/satisfaction/742655379/record/8282198633/3/

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hello,

Thank you for reaching out.

To help us look more closely into your inquiry, could you please send
us an email at ***@***.*** [1]? This will allow us to
assist you best.

Best regards,
Nasdaq Data Link


Links:
------
[1] ***@***.***

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/742655377/record/8282198624/1/
[3]
https://secure.helpscout.net/satisfaction/742655377/record/8282198624/2/
[4]
https://secure.helpscout.net/satisfaction/742655377/record/8282198624/3/
